name: Bicep Deploy Demo

on:
  workflow_dispatch:
  

env:
  rgLocation: 'centralus'
  rgName: 'rg-githubbicep-002'
  planName: 'plan-githubbicep-002'
  planSKUName: 'B3' 
  planSKUCapacity: 1
  planKind: 'linux'
  webappName: 'app-githubbicep-002'
  linuxFxVersion: '"node|16-lts"'
  templateFile: './Infra/main.bicep'
    
jobs:
  InfraPlan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'What happens if'
        shell: pwsh
        run: |
          az deployment sub create --location ${{ env.rgLocation }} `
                --template-file ${{ env.templateFile }} `
                --parameters rgName=${{ env.rgName }} `
                rgLocation=${{ env.rgLocation }} `
                planName=${{ env.planName }} `
                planSKUName=${{ env.planSKUName }} `
                planSKUCapacity=${{ env.planSKUCapacity }} `
                webAppName=${{ env.webappName }} `
                webAppLinuxFxVersion=${{ env.linuxFxVersion }} --what-if

  InfraDeploy:
    runs-on: ubuntu-latest
    needs: InfraPlan
    environment:
      name: InfraDeploy

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy Dev Resources with Bicep'
        shell: pwsh
        run: |
          az deployment sub create --location ${{ env.rgLocation }} `
                --template-file ${{ env.templateFile }} `
                --parameters rgName=${{ env.rgName }} `
                rgLocation=${{ env.rgLocation }} `
                planName=${{ env.planName }} `
                planSKUName=${{ env.planSKUName }} `
                planSKUCapacity=${{ env.planSKUCapacity }} `
                webAppName=${{ env.webappName }} `
                webAppLinuxFxVersion=${{ env.linuxFxVersion }}